services:
  backend:
    image: pcripsey/aaf-reporting-backend:latest
    ports:
      - '${BACKEND_HOST_PORT:-5000}:${BACKEND_CONTAINER_PORT:-5000}'
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_CONTAINER_PORT:-5000}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN:-http://localhost:3000}
    networks:
      - app-network

  frontend:
    image: pcripsey/aaf-reporting-frontend:latest
    ports:
      - '${FRONTEND_HOST_PORT:-3000}:80'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
